export { default as Navbar } from "./Navbar"
export { default as Header } from "./Header"
export { default as Featured } from "./Featured"
export { default as About } from "./About"
export { default as Gallery } from "./Gallery"
export { default as Footer } from "./Footer"
